### ISSUE TITLE
Cannot load colorscheme, 'c' a nil value

### ISSUE THREAD

**Issue by creativenull** [bkegley/gloombuddy#6]
Hey! I am getting this issue when I am trying to load the colorscheme:

```
.../lua/gloombuddy.lua:201: attempt to index global 'c' (a nil value)
```

Looks there are two places where `c` is used instead of `colors`, at line 201 and line 206 on `lua/gloombuddy.lua`, changing them to `colors` fixes the issue.

**Comment by bkegley** [comment]
fixed with #7
